# Generated by Django 4.1.2 on 2022-10-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/'),
            preserve_default=False,
        ),
    ]
